require 'test_helper'

class RailsDatabaseConfigTest < Minitest::Test
  def setup
    @config = build_config(
      'production' => {
        'primary' => { 'host' => 'primary.example.com', 'private_ip' => '10.0.0.10' },
        'standby' => [{ 'host' => 'standby.example.com', 'private_ip' => '10.0.0.11' }],
        'components' => {},
        'secrets' => {}
      }
    )
  end

  def test_generate_builds_primary_and_replica_configs
    result = ActivePostgres::Rails::DatabaseConfig.generate('production', app_name: 'demo_app', config: @config)

    assert_equal %w[primary primary_replica], result.keys
    assert_equal "<%= ENV.fetch('POSTGRES_PRIMARY_HOST') { '10.0.0.10' } %>", result['primary']['host']
    assert_equal "<%= ENV.fetch('POSTGRES_APPLICATION_NAME') { 'demo_app-primary' } %>", result['primary']['variables']['application_name']
    assert_equal true, result['primary_replica']['replica']
  end

  def test_generate_skips_replica_when_no_standby
    config = build_config(
      'production' => {
        'primary' => { 'host' => 'primary.example.com' },
        'standby' => [],
        'components' => {},
        'secrets' => {}
      }
    )

    result = ActivePostgres::Rails::DatabaseConfig.generate('production', app_name: 'demo', config: config)
    refute result.key?('primary_replica')
  end

  def test_render_returns_yaml_section
    output = ActivePostgres::Rails::DatabaseConfig.render('production', app_name: 'demo_app', config: @config)

    assert_includes output, 'production:'
    assert_includes output, 'primary:'
    assert_includes output, 'primary_replica:'
    assert_includes output, 'demo_app_production'
  end

  def test_render_partial_includes_comment_header
    output = ActivePostgres::Rails::DatabaseConfig.render_partial('production', app_name: 'demo_app', config: @config)

    assert_includes output, '# Generated by active_postgres'
    assert_includes output, 'production:'
  end

  private

  def build_config(overrides)
    ActivePostgres::Configuration.new(overrides, 'production')
  end
end
