require 'rails/generators'
require_relative '../../rails/database_config'

module ActivePostgres
  module Generators
    class InstallGenerator < ::Rails::Generators::Base
      source_root File.expand_path('templates', __dir__)

      desc 'Install active_postgres configuration files'

      def create_config_file
        template 'postgres.yml.erb', 'config/postgres.yml'
      end

      def update_database_yml
        if File.exist?('config/database.yml')
          contents = File.read('config/database.yml')

          # Extract production section
          production_section = contents[/^production:.*?(?=^[a-z_]+:|\z)/m] || ''

          # Check if we have the NEW Rails credentials-based config in production section
          if production_section.include?('Generated by active_postgres') && production_section.include?('Rails.application.credentials.dig(:postgres')
            say_status :skipped, 'config/database.yml already has ActivePostgres production config'
            return
          end

          # Check if old ENV-based config exists
          if production_section.include?('Generated by active_postgres') && production_section.include?('ENV.fetch')
            say_status :info, 'Found old ENV-based ActivePostgres config'
            return unless yes?('Replace with Rails credentials-based config? (y/n)', :yellow)
          end

          # Remove existing production section if present
          if contents =~ /^production:/m
            if contents.include?('Generated by active_postgres')
              say_status :info, 'Replacing ActivePostgres production config'
            else
              say_status :info, 'Found existing production config'
              return unless yes?('Replace with ActivePostgres config? (y/n)', :yellow)
            end

            lines = contents.lines
            new_lines = []
            skip_section = false
            skip_boring_comment = false

            lines.each do |line|
              # Skip the "Generated by active_postgres" comment before production section
              if line =~ /^# Generated by active_postgres/
                skip_boring_comment = true
                next
              end

              if line =~ /^production:/
                skip_section = true
                skip_boring_comment = false
                next
              elsif skip_section && (line =~ /^[a-z_]+:/ || line =~ /^# [A-Z]/)
                skip_section = false
              end

              new_lines << line unless skip_section || skip_boring_comment
            end

            # Remove trailing whitespace lines
            new_lines.pop while new_lines.last&.strip&.empty?
            contents = new_lines.join
          end

          # Append ActivePostgres production config directly
          contents += "\n" unless contents.end_with?("\n")
          contents += generate_production_config

          File.write('config/database.yml', contents)
          say_status :updated, 'config/database.yml (added ActivePostgres production config)'
        else
          create_file 'config/database.yml', <<~YAML
            default: &default
              adapter: postgresql
              encoding: unicode
              pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

            development:
              <<: *default
              database: #{boring_app_name}_development

            test:
              <<: *default
              database: #{boring_app_name}_test

            #{generate_production_config}
          YAML
        end
      end

      def show_credentials_template
        puts "\n📝 Add to Rails credentials (rails credentials:edit):"
        puts
        puts 'postgres:'
        puts '  # Rails application database credentials'
        puts "  username: #{boring_app_name}"
        puts "  password: \"#{generate_secure_password}\""
        puts "  database: #{boring_app_name}_production"
        puts '  primary_host: YOUR_PRIMARY_IP  # Update after provisioning (e.g., 10.8.0.100)'
        puts '  replica_host: YOUR_REPLICA_IP  # Update after provisioning (e.g., 10.8.0.101)'
        puts '  port: 5432'
        puts '  statement_timeout: 15s'
        puts "  application_name: #{boring_app_name}"
        puts
        puts '  # PostgreSQL server setup credentials (for active_postgres rake tasks)'
        puts "  superuser_password: \"#{generate_secure_password}\""
        puts "  replication_password: \"#{generate_secure_password}\""
        puts "  repmgr_password: \"#{generate_secure_password}\""
        puts
        puts '🔐 Secure passwords have been auto-generated above.'
        puts '📌 Update primary_host and replica_host with your actual IPs after provisioning.'
      end

      def show_next_steps
        puts "\n✅ ActivePostgres installed!"
        puts "\n📝 Next steps:"
        puts '  1. Either:'
        puts '     a) Edit config/postgres.yml with your database servers, OR'
        puts '     b) Use Terraform to auto-generate config/postgres.yml'
        puts '  2. Add secrets to Rails credentials (see above)'
        puts '  3. Deploy PostgreSQL HA: rails active_postgres:setup'
        puts '  4. Check health: rails active_postgres:health'
        puts "\n📚 See config/postgres.example.yml in gem for full examples"
      end

      private

      def boring_app_name
        @boring_app_name ||= begin
          if defined?(::Rails) && ::Rails.application
            ::Rails.application.class.module_parent_name.underscore
          else
            File.basename(destination_root).tr('- ', '_')
          end
        rescue StandardError
          'app'
        end
      end

      def generate_production_config
        # Generate the production config using Rails credentials
        # ERB values are quoted to prevent YAML parser confusion with colons
        app_name = boring_app_name
        <<~YAML
          # Generated by active_postgres. Update Rails credentials (rails credentials:edit) to change values.
          production:
            primary:
              <<: *default
              username: "<%= Rails.application.credentials.dig(:postgres, :username) || '#{app_name}' %>"
              password: "<%= Rails.application.credentials.dig(:postgres, :password) %>"
              database: "<%= Rails.application.credentials.dig(:postgres, :database) || '#{app_name}_production' %>"
              host: "<%= Rails.application.credentials.dig(:postgres, :primary_host) || 'localhost' %>"
              port: "<%= Rails.application.credentials.dig(:postgres, :port) || 5432 %>"
              variables:
                statement_timeout: "<%= Rails.application.credentials.dig(:postgres, :statement_timeout) || '15s' %>"
                application_name: "<%= Rails.application.credentials.dig(:postgres, :application_name) || '#{app_name}-primary' %>"
            primary_replica:
              <<: *default
              username: "<%= Rails.application.credentials.dig(:postgres, :username) || '#{app_name}' %>"
              password: "<%= Rails.application.credentials.dig(:postgres, :password) %>"
              database: "<%= Rails.application.credentials.dig(:postgres, :database) || '#{app_name}_production' %>"
              host: "<%= Rails.application.credentials.dig(:postgres, :replica_host) %>"
              port: "<%= Rails.application.credentials.dig(:postgres, :port) || 5432 %>"
              replica: true
              variables:
                statement_timeout: "<%= Rails.application.credentials.dig(:postgres, :statement_timeout) || '15s' %>"
                application_name: "<%= Rails.application.credentials.dig(:postgres, :application_name) || '#{app_name}-replica' %>"
        YAML
      end

      def generate_secure_password(length: 32)
        require 'securerandom'
        # Generate a secure password with letters, numbers, and safe special characters
        # Avoiding quotes and backslashes that could cause issues in YAML/shell
        chars = [*'A'..'Z', *'a'..'z', *'0'..'9', *'!@#$%^&*()-_=+[]{}|;:,.<>?/~'.chars]
        Array.new(length) { chars.sample }.join
      end
    end
  end
end
